// plugins/assets/src/spa/app/components/AssetListItem.tsx
import type { TreeNode } from '../utils/tree'
import { useState } from 'preact/hooks'
import { TYPE_META } from '../utils/assetType'
import { Checkbox } from './ui/Checkbox'
import { Icon } from './ui/Icon'

export interface AssetListItemProps {
  node: TreeNode
  depth?: number
  selectedPath?: string
  selectable?: boolean
  selectedPaths?: Set<string>
  onSelectToggle?: (path: string) => void
  onSelect: (node: TreeNode) => void
}

export function AssetListItem({ node, depth = 0, selectedPath, selectable, selectedPaths, onSelectToggle, onSelect }: AssetListItemProps) {
  const [open, setOpen] = useState(true)
  const icon = node.isFolder ? 'i-ph-folder-duotone' : TYPE_META[node.asset?.type ?? 'other'].icon
  const isActive = !node.isFolder && node.asset?.path === selectedPath

  return (
    <div>
      <button
        type="button"
        class={`flex w-full items-center gap-2 border-b border-base px-4 py-1 text-sm hover:bg-active ${isActive ? 'bg-active' : ''}`}
        style={{ paddingLeft: `${1 + depth * 1.25}rem` }}
        onClick={() => (node.isFolder ? setOpen(o => !o) : onSelect(node))}
      >
        {selectable && !node.isFolder && (
          <Checkbox
            checked={selectedPaths?.has(node.path)}
            onClick={e => e.stopPropagation()}
            onChange={() => onSelectToggle?.(node.path)}
          />
        )}
        <Icon name={icon} />
        <span class="flex-1 truncate text-left font-mono">{node.name}</span>
        {node.isFolder && <Icon name="i-ph-caret-right" class={`transition ${open ? 'rotate-90' : ''}`} />}
      </button>
      {node.isFolder && open && node.children.map(child => (
        <AssetListItem
          key={child.path}
          node={child}
          depth={depth + 1}
          selectedPath={selectedPath}
          selectable={selectable}
          selectedPaths={selectedPaths}
          onSelectToggle={onSelectToggle}
          onSelect={onSelect}
        />
      ))}
    </div>
  )
}

// plugins/assets/src/spa/app/components/AssetListItem.vue
<script setup lang="ts">
import type { TreeNode } from '../utils/tree'
import FormCheckbox from '@antfu/design/components/Form/FormCheckbox.vue'
import { computed, ref } from 'vue'
import { TYPE_META } from '../utils/assetType'

defineOptions({ name: 'AssetListItem' })

const props = withDefaults(defineProps<{
  node: TreeNode
  depth?: number
  selectedPath?: string
  selectable?: boolean
  selectedPaths?: Set<string>
}>(), { depth: 0 })

const emit = defineEmits<{
  select: [node: TreeNode]
  selectToggle: [path: string]
}>()

const open = ref(true)
const icon = computed(() => (props.node.isFolder ? 'i-ph-folder-duotone' : TYPE_META[props.node.asset?.type ?? 'other'].icon))
const isActive = computed(() => !props.node.isFolder && props.node.asset?.path === props.selectedPath)

function onActivate(): void {
  if (props.node.isFolder)
    open.value = !open.value
  else
    emit('select', props.node)
}
</script>

<template>
  <div>
    <div
      class="flex w-full items-center gap-2 border-b border-base px-4 py-1 text-sm hover:bg-active"
      :class="isActive ? 'bg-active' : 'cursor-pointer'"
      :style="{ paddingLeft: `${1 + depth * 1.25}rem` }"
      role="button"
      tabindex="0"
      @click="onActivate"
      @keydown.enter="onActivate"
    >
      <span v-if="selectable && !node.isFolder" @click.stop>
        <FormCheckbox :model-value="selectedPaths?.has(node.path)" @update:model-value="emit('selectToggle', node.path)" />
      </span>
      <span :class="icon" />
      <span class="flex-1 truncate text-left font-mono">{{ node.name }}</span>
      <span v-if="node.isFolder" class="i-ph-caret-right transition" :class="open ? 'rotate-90' : ''" />
    </div>
    <template v-if="node.isFolder && open">
      <AssetListItem
        v-for="child in node.children"
        :key="child.path"
        :node="child"
        :depth="depth + 1"
        :selected-path="selectedPath"
        :selectable="selectable"
        :selected-paths="selectedPaths"
        @select="emit('select', $event)"
        @select-toggle="emit('selectToggle', $event)"
      />
    </template>
  </div>
</template>
