// plugins/assets/src/spa/app/components/FontPreview.tsx
import type { AssetInfo } from '../../../types'
import { useEffect, useId } from 'preact/hooks'

export interface FontPreviewProps {
  asset: AssetInfo
  class?: string
}

/** Loads the font via a scoped `@font-face` and renders a pangram-ish sample. */
export function FontPreview({ asset, class: extra }: FontPreviewProps) {
  const family = `devframe-assets-${useId().replace(/[^a-z0-9]/gi, '')}`

  useEffect(() => {
    const style = document.createElement('style')
    style.textContent = `@font-face { font-family: '${family}'; src: url('${asset.publicPath}'); }`
    document.head.append(style)
    return () => style.remove()
  }, [family, asset.publicPath])

  return (
    <div class={['overflow-hidden', extra].filter(Boolean).join(' ')} style={{ fontFamily: `'${family}'` }}>
      Aa Bb Cc Dd Ee Ff Gg Hh Ii Jj Kk Ll Mm Nn Oo Pp Qq Rr Ss Tt Uu Vv Ww Xx Yy Zz
    </div>
  )
}

// plugins/assets/src/spa/app/components/FontPreview.vue
<script setup lang="ts">
import type { AssetInfo } from '../../../types'
import { onBeforeUnmount, onMounted, watch } from 'vue'

const props = defineProps<{ asset: AssetInfo }>()

// A scoped, unique family so multiple font previews don't clash.
const family = `devframe-assets-${Math.random().toString(36).slice(2)}`
let styleEl: HTMLStyleElement | null = null

function apply(url: string): void {
  if (!styleEl) {
    styleEl = document.createElement('style')
    document.head.append(styleEl)
  }
  styleEl.textContent = `@font-face { font-family: '${family}'; src: url('${url}'); }`
}

onMounted(() => apply(props.asset.publicPath))
watch(() => props.asset.publicPath, url => apply(url))
onBeforeUnmount(() => styleEl?.remove())
</script>

<template>
  <div class="overflow-hidden" :style="{ fontFamily: `'${family}'` }">
    Aa Bb Cc Dd Ee Ff Gg Hh Ii Jj Kk Ll Mm Nn Oo Pp Qq Rr Ss Tt Uu Vv Ww Xx Yy Zz
  </div>
</template>
